---
title: "Power Analysis"
author: "Sam Manski"
format: html
editor: visual
---

## C1380 Power Analysis

Power in two-one-sided t-tests (TOST) procedure for testing equivalence and in one-sided t-tests for non-superiority are based on the significance level, $\alpha$, the equivalence threshold, the sample size, the difference in means between groups, and the standard deviation of the response. Therefore, we calculate the power of the equivalence and non-inferiority procedures under varying equivalence thresholds, differences in means, and standard deviations, for two proposed sample sizes (N = 62 or N = 100).

| Equivalence Threshold | Observed Difference | Response SD | Equivalence Power N = 62 | Equivalence Power N = 100 | Non-superiority Power N = 62 | Non-superiority Power N = 100 |
|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
| 1.5 | 0.25 | 2.25 | 0.614 | 0.854 | 0.861 | 0.973 |
| 1.5 | 0.5 | 2.25 | 0.499 | 0.710 | 0.683 | 0.875 |
| 1.5 | 0.75 | 2.25 | 0.352 | 0.504 | 0.447 | 0.646 |
| 1.5 | 1 | 2.25 | 0.214 | 0.294 | 0.229 | 0.343 |
| 2 | 0.25 | 2.25 | 0.904 | 0.986 | 0.989 | 0.999 |
| 2 | 0.5 | 2.25 | 0.825 | 0.952 | 0.955 | 0.997 |
| 2 | 0.75 | 2.25 | 0.697 | 0.867 | 0.861 | 0.973 |
| 2 | 1 | 2.25 | 0.533 | 0.713 | 0.683 | 0.875 |

```{r}
library(PowerTOST)
library(tidyverse)
thresholds <- c(1.5, 2)
diffs <- c(0.25, 0.5, 0.75, 1, 1.25)
sds <- c(2, 2.25, 2.5)
ns <- c(74, 100)

#thresholds <- c(1.5, 2)
#diffs <- c(0.25, 0.5, 0.75, 1)
#sds <- c(2.25)
#ns <- c(62, 100)

results <- as.data.frame(matrix(ncol = 6))
names(results) <- c("n", "threshold", "difference", "sd", "equiv_power", "ns_power")
for(n in ns){
  for(t in thresholds){
    for(d in diffs){
      for(s in sds){

          p_equiv<- power.TOST(alpha = 0.05, logscale = FALSE, theta0 = d, theta1 = -t, theta2 = t, CV = s, n=n, design = "parallel", method = "exact")
          p_nonsup <- power.noninf(alpha = 0.025, logscale = FALSE, theta0 = d, margin = t, CV = s, n = n)
      results<- rbind(results, c(n, t, d, s, p_equiv, p_nonsup))
      }
    }
  }
}
results <- results[-1,]
results_longer <- results %>% pivot_wider(names_from = n, values_from = c(equiv_power, ns_power))

```

## Equivalence vs Non-superiority

A non-superiority test essentially tries to show that one treatment is non-superior to another (in this case Liposomal Bupivacaine being non-superior to Bupivacaine HCl). In other words, this would be used to show that Liposomal Bupivacaine has no clinically relevant advantage over Bupivacaine HCl in terms of pain management. This contrasts the hypothesis of an equivalence test which would be used to show that the two treatments are functionally equivalent, meaning that Liposomal Bupivacaine has no clinically relevant advantage over Bupivacaine HCl, and vice versa. The advantage of the non-superiority test over the equivalence test is that being a one-sided test, non-superiority will have higher power for the same sample size as compared to an equivalence test. Therefore, we may be able to leverage this methodological decision to reduce your required sample size while still addressing your primary hypothesis.

## Choice of Representative Values

A range of estimates for the minimal clinically important difference (MCID) exist in the literature. Values for this difference include 1.65 (Bahreini et al 2020), 1.74 or 2 (Farrar et al 2001), 2.5 (Dale et al, 2020), 1.3 (Kim et al, 2022), or between 1.3 and 2 (Dinges et al, 2021). Confirming these values, various studies report no significant difference in pain when mean differences are below 1 (Ferreira-Valente et al, 2011 and Subramaniam et al, 2023). We therefore use 1.5 and 2 as representative values for MCID.

Pain scores within samples are highly variable and it is important to estimate the standard deviation of the response variable. Our literature review supports an estimated standard deviation of pain scores between 2 and 2.5 (Hussain et al, 2021, Dinges et al, 2021, Dale et al, 2020, and Ferreira-Valente et al, 2011). We choose 2, 2.25, and 2.5 as representative values for this standard deviation.

Example observed differences in pain scores between Liposomal Bupivacaine and Bupivacaine HCl can be found in meta-analyses by Hussain et al (2021) and Dinges et al (2021). Hussain et al reports mean differences between groups averaged over 9 studies between 0.2 and 0.5. Dinges et al. reports differences in mean pain between groups for 16 studies where differences ranged from -1.7 to 0.21 (mean -0.55) at 24h and -1.9 to 1.1 (mean -0.37) at 72h. We choose representative values of 0.25, 0.5, 0.75, and 1 for these differences.
